# Generated by Django 5.2.8 on 2025-11-10 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empregado',
            options={'verbose_name': 'empregado', 'verbose_name_plural': 'empregados'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'cargo', 'verbose_name_plural': 'cargos'},
        ),
        migrations.AlterField(
            model_name='empregado',
            name='codigo',
            field=models.CharField(max_length=3, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='nome_completo',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='numero',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empregados', to='CRUD_Registro.position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Título'),
        ),
    ]
