# Generated by Django 5.2.8 on 2025-11-10 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_Registro', '0002_alter_empregado_options_alter_position_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do cargo')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do departamento')),
                ('sigla', models.CharField(max_length=10, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.RemoveField(
            model_name='empregado',
            name='position',
        ),
        migrations.RenameField(
            model_name='empregado',
            old_name='numero',
            new_name='telefone',
        ),
        migrations.AlterField(
            model_name='empregado',
            name='codigo',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='empregado',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empregados', to='CRUD_Registro.cargo', verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='empregado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empregados', to='CRUD_Registro.departamento', verbose_name='Departamento'),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
